# Generated by Django 2.0.6 on 2018-11-30 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Champion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('alias', models.CharField(max_length=100)),
                ('quote', models.CharField(max_length=255)),
                ('biography', models.TextField()),
                ('role', models.IntegerField(choices=[(1, 'Fighter'), (2, 'Assassin'), (3, 'Tank'), (4, 'Mage'), (5, 'Marksman'), (6, 'Support')], default=0)),
                ('youtube_video_id', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
