# Generated by Django 2.0.6 on 2018-11-30 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='champion',
            name='image',
            field=models.ImageField(blank=True, upload_to='champions_images/'),
        ),
        migrations.AddField(
            model_name='champion',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
