# Generated by Django 2.0.6 on 2018-11-30 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('champs', '0002_auto_20181130_1354'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='champion',
            name='image',
        ),
        migrations.AddField(
            model_name='champion',
            name='avatar',
            field=models.ImageField(blank=True, upload_to='champions_avatars/'),
        ),
        migrations.AddField(
            model_name='champion',
            name='wallpaper',
            field=models.ImageField(blank=True, upload_to='champions_wallpapers/'),
        ),
    ]
